using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace ContosoUniversity.Models
{
    public class Course
    {
        // Question? 1.What does this DatabaseGenerated annotation do?
        //Note: The DatabaseGenerated attribute allows the app to specify the primary key rather than having the database generate it.
        //     In other words, the PK is provided by the application rather than generated by the database.
        //     For Course entities, the user specifies the PK. 
        //     For example, a course number such as a 1000 series for the math department, a 2000 series for the English department.
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Display(Name = "Number")]
        public int CourseID { get; set; }
        [StringLength(50, MinimumLength = 3)]
        public string Title { get; set; }
        [Range(0, 5)]
        public int Credits { get; set; }

        //The Course entity has a foreign key (FK) property DepartmentID. DepartmentID points to the related Department entity.
        public int DepartmentID { get; set; }

        //Course can have only one department
        public Department Department { get; set; }

        //Course can have any number of students enrolled in it
        public ICollection<Enrollment> Enrollments { get; set; }
        //A course may be taught by multiple instructors, so the CourseAssignments navigation property is a collection
        public ICollection<CourseAssignment> CourseAssignments { get; set; }
    }
}
